FROM nginx:1.15

RUN apt-get update
RUN apt-get install -y zip

ADD ./poll_gui.zip /
RUN unzip /poll_gui.zip -d /
RUN cp -R /dist/* /usr/share/nginx/html

ADD ./nginx /etc/nginx/conf.d
ADD ./nginx/pollgui.nginx.conf /etc/nginx/nginx.conf
