version: '2.0'

services:
  poll_gui_server:
    container_name: poll_gui_server
    restart: unless-stopped
    image: ds_poll_gui
    environment:
    - OPAL_SERVER_IP=${OPAL_SERVER_IP} # define timeout for requests
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ds_opal_opal_net
  poll_server:
    container_name: poll_server
    image: ds_poll
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - ds_opal_opal_net
    volumes:
      - ./src:/root/src
      - ../ds_poll:/root/ds_poll
      - ../ds_common:/root/ds_common
    env_file:
      - config_service.env
      - config_db.env

networks:
  ds_opal_opal_net:
    external: true