version: '3.5'

services:

  queue_server:
    container_name: queue_server
    image: python:3
    volumes:
      - ../ds_queue:/root/ds_queue
      - ../ds_common:/root/ds_common
    networks:
      - ds_opal_opal_net
    ports:
      - "8001:8001"
    command: bash -c "tail -f /dev/null"

  poll_server:
    container_name: poll_server
    image: ds_poll
    restart: unless-stopped
    depends_on:
      - db
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - ds_opal_opal_net
      - backend
    links:
      - db
    volumes:
      - ./src:/root/src
      - ../ds_poll:/root/ds_poll
      - ../ds_common:/root/ds_common
    env_file:
      - config_service.env
      - config_db.env
    command: bash -c "cd /root/src && chmod +x startup.dev.sh && ./startup.dev.sh"

  db:
    container_name: poll_monitor_db
    restart: unless-stopped
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - config_db.env
    ports:
      - "5433:5432"
    volumes:
      - ./service_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  mongodb:
    container_name: poll_monitor_mongodb
    image: mongo:3.6
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "27018" # process
      - "28017" # http
    ports:
      - "127.0.0.1:27018:27017"
      - "127.0.0.1:28017:28017"

networks:
  ds_opal_opal_net:
    external: true
  backend: