version: '3.2'

services:

  caid_service:
    container_name: caid_service
    image: python:3
    restart: unless-stopped
    depends_on:
      - db
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - backend
    links:
      - db
    volumes:
      - ../src:/root/src
    env_file:
      - config_caidService.env
      - config_db.env
    command: bash -c "cd /root/src && chmod +x startup.dev.sh && ./startup.dev.sh"

  db:
    container_name: caid_db
    restart: unless-stopped
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - config_db.env
    ports:
      - "5433:5432"
    volumes:
      - ./caid_service_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  mongodb:
    container_name: caid_mongodb
    build:
      context: .
      dockerfile: Dockerfile.mongo
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "27017" # process
      - "28017" # http
    ports:
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:28017:28017"

networks:
  backend: